In [13]:
import tensorflow as tf
import pandas as pd
import numpy as np


In [39]:
d = {
    'U1': [5, 3, np.nan, 1],
    'U2': [4, np.nan, np.nan, 1],
    'U3': [1, 1, np.nan, 5],
    'U4': [1, np.nan, np.nan, 4],
    'U5': [np.nan, 1, 5, 4]
}
df = pd.DataFrame(data=d, index=['D1', 'D2', 'D3', 'D4']).transpose()
mtx = df.fillna(0).as_matrix().astype(np.float32)
mtx

array([[ 5.,  3.,  0.,  1.],
       [ 4.,  0.,  0.,  1.],
       [ 1.,  1.,  0.,  5.],
       [ 1.,  0.,  0.,  4.],
       [ 0.,  1.,  5.,  4.]], dtype=float32)

In [40]:
np_mask = df.notnull()
np_mask.values

array([[ True,  True, False,  True],
       [ True, False, False,  True],
       [ True,  True, False,  True],
       [ True, False, False,  True],
       [False,  True,  True,  True]], dtype=bool)

mtx = p.dot(q.T) = mtx_est

In [41]:
n_dim = mtx.shape[0]
m_dim = mtx.shape[1]
k = 2

p = np.random.rand(n_dim, k).astype(np.float32)
q = np.random.rand(m_dim, k).astype(np.float32)

In [43]:
assert mtx.dtype == np.float32
assert mtx.shape == (5, 4)

tf_mask = tf.Variable(np_mask.values)

mtx_ph = tf.placeholder(dtype=tf.float32, shape=mtx.shape, name='inp_mtx_ph')

p_t = tf.Variable(initial_value=p, trainable=True, name='p_matrix')
q_t = tf.Variable(initial_value=q, trainable=True, name='q_matrix')
pqdot_t = tf.matmul(p_t, q_t, transpose_a=False, transpose_b=True)
loss = tf.reduce_sum(tf.square((tf.boolean_mask(mtx_ph, tf_mask) - tf.boolean_mask(pqdot_t, tf_mask))))

gradient_step = tf.train.GradientDescentOptimizer(learning_rate=.0002)
train = gradient_step.minimize(loss)

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    for step in range(5000):
        sess.run(train, feed_dict={mtx_ph: mtx})
        if step % 1000 == 0:
            print('Step: %i loss: %f' % (step, sess.run(loss, feed_dict={mtx_ph: mtx})))
        
    a = sess.run(pqdot_t)
    print(a)



Step: 0 loss: 100.836136


Step: 1000 loss: 28.418032


Step: 2000 loss: 19.452719


Step: 3000 loss: 0.650289


Step: 4000 loss: 0.236160


[[ 5.02362537  2.93818951  4.18982077  0.99471891]
 [ 3.97791243  2.33414936  3.50238371  0.99227667]
 [ 1.07790232  0.80703026  5.20754099  4.9862833 ]
 [ 0.96085811  0.70238823  4.22705317  3.98509645]
 [ 1.89616084  1.24539995  4.90896702  4.06156635]]


In [27]:
np.square(mtx)

array([[ 25.,   9.,   0.,   1.],
       [ 16.,   0.,   0.,   1.],
       [  1.,   1.,   0.,  25.],
       [  1.,   0.,   0.,  16.],
       [  0.,   1.,  25.,  16.]], dtype=float32)