In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np


/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


In [6]:
d = {
    'U1': [3, 5, np.nan, 2],
    'U2': [4, np.nan, np.nan, 1],
    'U3': [5, 4, np.nan, 1],
    'U4': [1, np.nan, np.nan, 3],
    'U5': [np.nan, 5, 2, 2]
}
df = pd.DataFrame(data=d, index=['D1', 'D2', 'D3', 'D4']).transpose()
mtx = df.fillna(0).as_matrix().astype(np.float32)
df

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>D1</th>
      <th>D2</th>
      <th>D3</th>
      <th>D4</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>U1</th>
      <td>3.0</td>
      <td>5.0</td>
      <td>NaN</td>
      <td>2.0</td>
    </tr>
    <tr>
      <th>U2</th>
      <td>4.0</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>1.0</td>
    </tr>
    <tr>
      <th>U3</th>
      <td>5.0</td>
      <td>4.0</td>
      <td>NaN</td>
      <td>1.0</td>
    </tr>
    <tr>
      <th>U4</th>
      <td>1.0</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>3.0</td>
    </tr>
    <tr>
      <th>U5</th>
      <td>NaN</td>
      <td>5.0</td>
      <td>2.0</td>
      <td>2.0</td>
    </tr>
  </tbody>
</table>
</div>

In [3]:
np_mask = df.notnull()
np_mask.values

array([[ True,  True, False,  True],
       [ True, False, False,  True],
       [ True,  True, False,  True],
       [ True, False, False,  True],
       [False,  True,  True,  True]], dtype=bool)

mtx = p.dot(q.T) = mtx_est

In [4]:
n_dim = mtx.shape[0]
m_dim = mtx.shape[1]
k = 2

p = np.random.rand(n_dim, k).astype(np.float32)
q = np.random.rand(m_dim, k).astype(np.float32)

In [5]:
assert mtx.dtype == np.float32
assert mtx.shape == (5, 4)

tf_mask = tf.Variable(np_mask.values)

mtx_ph = tf.placeholder(dtype=tf.float32, shape=mtx.shape, name='inp_mtx_ph')

p_t = tf.Variable(initial_value=p, trainable=True, name='p_matrix')
q_t = tf.Variable(initial_value=q, trainable=True, name='q_matrix')
pqdot_t = tf.matmul(p_t, q_t, transpose_a=False, transpose_b=True)
loss = tf.reduce_sum(tf.square((tf.boolean_mask(mtx_ph, tf_mask) - tf.boolean_mask(pqdot_t, tf_mask))))

gradient_step = tf.train.GradientDescentOptimizer(learning_rate=.0002)
train = gradient_step.minimize(loss)

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    for step in range(5000):
        sess.run(train, feed_dict={mtx_ph: mtx})
        if step % 1000 == 0:
            print('Step: %i loss: %f' % (step, sess.run(loss, feed_dict={mtx_ph: mtx})))
        
    a = sess.run(pqdot_t)
    print(a)



Step: 0 loss: 114.367157


Step: 1000 loss: 6.325691


Step: 2000 loss: 1.294454


Step: 3000 loss: 0.239016


Step: 4000 loss: 0.121432


[[ 3.05027962  4.91120434  2.02590656  2.14397955]
 [ 4.00160837  3.80701113  1.19917059  1.02755392]
 [ 4.95264482  4.09068346  1.14047599  0.85113382]
 [ 0.99531931  4.87123823  2.46979022  2.91321564]
 [ 3.42113543  4.98923016  1.98498368  2.05311251]]


## Now SVD factorization (middle matrix tells how much reduce dimensions)

In [45]:
from numpy import linalg

M = pd.DataFrame([
    [5.0, 3.0, 0.0, 2.0, 2.0, 2.0],
    [4.0, 3.0, 4.0, 0.0, 3.0, 3.0],
    [5.0, 2.0, 5.0, 2.0, 1.0, 1.0],
    [3.0, 5.0, 3.0, 0.0, 1.0, 1.0],
    [3.0, 3.0, 3.0, 2.0, 4.0, 5.0],
    [2.0, 3.0, 2.0, 3.0, 5.0, 5.0]]
    , columns=['mib', 'st', 'av', 'b', 'ss', 'lm']
    , index=['Sara', 'Jesper', 'Therese', 'Helle', 'Pietro', 'Ekaterina'])

M

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>mib</th>
      <th>st</th>
      <th>av</th>
      <th>b</th>
      <th>ss</th>
      <th>lm</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Sara</th>
      <td>5.0</td>
      <td>3.0</td>
      <td>0.0</td>
      <td>2.0</td>
      <td>2.0</td>
      <td>2.0</td>
    </tr>
    <tr>
      <th>Jesper</th>
      <td>4.0</td>
      <td>3.0</td>
      <td>4.0</td>
      <td>0.0</td>
      <td>3.0</td>
      <td>3.0</td>
    </tr>
    <tr>
      <th>Therese</th>
      <td>5.0</td>
      <td>2.0</td>
      <td>5.0</td>
      <td>2.0</td>
      <td>1.0</td>
      <td>1.0</td>
    </tr>
    <tr>
      <th>Helle</th>
      <td>3.0</td>
      <td>5.0</td>
      <td>3.0</td>
      <td>0.0</td>
      <td>1.0</td>
      <td>1.0</td>
    </tr>
    <tr>
      <th>Pietro</th>
      <td>3.0</td>
      <td>3.0</td>
      <td>3.0</td>
      <td>2.0</td>
      <td>4.0</td>
      <td>5.0</td>
    </tr>
    <tr>
      <th>Ekaterina</th>
      <td>2.0</td>
      <td>3.0</td>
      <td>2.0</td>
      <td>3.0</td>
      <td>5.0</td>
      <td>5.0</td>
    </tr>
  </tbody>
</table>
</div>

In [56]:
U, Sigma, Vt = linalg.svd(M)
print(np.sum(Sigma))
print('90p of information vs 4-dim amount of information %f vs %f' % (np.sum(Sigma)*.9, np.sum(Sigma[:4])))
Sigma


32.0339920548
90p of information vs 4-dim amount of information 28.830593 vs 29.809608


array([ 17.26966149,   5.84468211,   3.56288086,   3.13238351,
         1.66833703,   0.55604707])

#### Rule dimension reduction should preserve 90% of data so above should be reduced to 4 dim

In [65]:
def rank_k(k):
    U_reduced = np.mat(U[:, :k])
    Vt_reduced = np.mat(Vt[:k, :])
    Sigma_reduced = np.eye(k) * Sigma[:k]
    return U_reduced, Sigma_reduced, Vt_reduced

U_reduced, Sigma_reduced, Vt_reduced = rank_k(4)
M_hat = U_reduced * Sigma_reduced * Vt_reduced
pd.DataFrame(M_hat, columns=['mib', 'st', 'av', 'b', 'ss', 'lm'], index=['Sara', 'Jesper', 'Therese', 'Helle', 'Pietro', 'Ekaterina'])

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>mib</th>
      <th>st</th>
      <th>av</th>
      <th>b</th>
      <th>ss</th>
      <th>lm</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Sara</th>
      <td>4.871471</td>
      <td>3.114441</td>
      <td>0.048933</td>
      <td>2.238701</td>
      <td>1.940838</td>
      <td>1.920736</td>
    </tr>
    <tr>
      <th>Jesper</th>
      <td>3.493447</td>
      <td>3.457876</td>
      <td>4.190671</td>
      <td>0.948861</td>
      <td>2.615216</td>
      <td>2.820324</td>
    </tr>
    <tr>
      <th>Therese</th>
      <td>5.221119</td>
      <td>1.803411</td>
      <td>4.915722</td>
      <td>1.589691</td>
      <td>1.095281</td>
      <td>1.142054</td>
    </tr>
    <tr>
      <th>Helle</th>
      <td>3.253511</td>
      <td>4.773152</td>
      <td>2.903842</td>
      <td>-0.472145</td>
      <td>1.141579</td>
      <td>1.134556</td>
    </tr>
    <tr>
      <th>Pietro</th>
      <td>2.930617</td>
      <td>3.047005</td>
      <td>3.031127</td>
      <td>2.111370</td>
      <td>4.295268</td>
      <td>4.670798</td>
    </tr>
    <tr>
      <th>Ekaterina</th>
      <td>2.272710</td>
      <td>2.766644</td>
      <td>1.893157</td>
      <td>2.504730</td>
      <td>4.915963</td>
      <td>5.351620</td>
    </tr>
  </tbody>
</table>
</div>